services:
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile # on move to prod, update this
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - db
    networks:
      - db
      - app
    restart: unless-stopped

  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:3000"
    networks:
      - app
    restart: unless-stopped

networks:
  app:
  db:
    driver: bridge
volumes:
  db_data:
