name: Test if it builds
on:
  push:
    branches:
      - main
  pull_request:
    types:
        - opened
    

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: bun install
      - run: bun run build
